default: &default
  adapter: postgresql
  encoding: utf8
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: 10
  timeout: 5000
  host: <%= ENV['POSTGRES_HOST'] %>
  port: 5432

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>

test:
  <<: *default
  database: <%= ENV['POSTGRES_TEST_DB'] %>

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
